version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-todo-db
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: todo_db
    ports:
      - "3306:3306"